blank_issues_enabled: false
contact_links:
  - name: Steam Workshop
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=3597784225
    about: Visit the Steam Workshop page for discussions and updates
